export const REVIEW_PERIOD_STATUSES = Object.freeze({
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
});

export const REVIEW_PERIOD_NAME_MAX_LENGTH = 120;
export const REVIEW_PERIOD_DESCRIPTION_MAX_LENGTH = 500;

export const PERFORMANCE_REVIEW_RATING_MIN = 1;
export const PERFORMANCE_REVIEW_RATING_MAX = 5;
export const PERFORMANCE_REVIEW_COMMENT_MAX_LENGTH = 1000;
